# Generated by Django 3.1.7 on 2021-04-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField(default='2021-04-04')),
                ('country', models.CharField(choices=[('Europe', (('FR', 'France'), ('ES', 'Spain'), ('TR', 'Turkey'))), ('Africa', (('MA', 'Morocco'), ('DZ', 'Algeria'), ('NG', 'Nigeria'))), ('Asia', (('CN', 'China'), ('MH', 'Malaysia'), ('RU', 'Russia')))], default='Turkey', max_length=20)),
                ('productID', models.DecimalField(decimal_places=0, default=11111, max_digits=8)),
                ('year', models.CharField(choices=[(2021, 2021)], default='2021', max_length=20)),
            ],
        ),
    ]
