# Generated by Django 3.1.7 on 2021-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='year',
            field=models.CharField(choices=[('2000', '2000'), ('2005', '2005'), ('2010', '2010'), ('2015', '2015'), ('2020', '2020')], default='2020', max_length=20),
        ),
    ]
