# Generated by Django 3.1.7 on 2021-04-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
