version: '3'
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: docker_postgres
            POSTGRES_USER: docker_user
            POSTGRES_PASSWORD: puente123
        ports:
            - 5433:5432